In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("../data/train.csv")

In [9]:
dataset[:20]

,company1,company2,is_parent,snippet
0,Sprint_Corporation,Verizon_Communications,False,1 wireless carrier Verizon_Communications (NY...
1,Sprint_Corporation,Verizon_Communications,False,"While AT&T, Sprint_Corporation, and T-Mobile ..."
2,Sprint_Corporation,Verizon_Communications,False,"\nAT&T, Sprint_Corporation, and Verizon_Commun..."
3,Alexa_Internet,Amazon.com,False,Logitech addsAmazon.comn'sAlexa_Interneta skil...
4,Alexa_Internet,Amazon.com,False,\nLogitech has announced a new version of the ...
5,Alexa_Internet,Amazon.com,False,"Say ""Alexa_Internet,"" and you can access any ..."
6,Lufthansa,British_Airways,False,"''\nGary Leff, author of the blog, View From T..."
7,Asda,Walmart,False,It is understood that B&M has no knowledge of...
8,The_Walt_Disney_Company,Marvel_Comics,True,"""\nSony spent a hefty $175 million to make the..."
9,Comcast,Verizon_Communications,False,wireless industry to ease pricing pressure in...
10,Comcast,Verizon_Communications,False,O ) are also entering the market with wireless...
11,Comcast,Verizon_Communications,False,"\n""With no merger of Sprint and T-Mobile, as w..."
12,AOL,Verizon_Communications,False,The closure follows an acquisition of the par...
13,AOL,Verizon_Communications,False,\nRead More: Will Verizon_Communications's Big...
14,AOL,Verizon_Communications,False,"""\nThe company said AOL delivered ""strong reve..."
15,PrimeSense,Apple_Inc.,False,Apple_Inc. made few acquisitions related to A...
16,PrimeSense,Apple_Inc.,False,Apple_Inc. made few acquisitions related to A...
17,Sprint_Corporation,T-Mobile_US,False,"carriers lift fees to Belgium NEW YORK—AT&T, ..."
18,Google,YouTube,True,\nGeofeedia also drew on information from Goog...
19,Google,YouTube,True,\nGeofeedia also drew on information from Goog...

In [7]:
dataset["is_parent"].value_counts()

False    62881
True     26571
Name: is_parent, dtype: int64

In [8]:
dataset.describe()

,company1,company2,is_parent,snippet
count,89452,89452,89452,89452
unique,440,447,2,52175
top,Google,YouTube,False,\nFollow Business Insider Australia on Faceboo...
freq,7348,13001,62881,271

In [10]:
dataset["company1"].value_counts()

Google                          7348
YouTube                         5347
Twitter                         4836
Amazon.com                      4596
Facebook                        3604
Verizon_Communications          3236
Alexa_Internet                  2977
Sprint_Corporation              2763
Apple_Inc.                      2694
The_Walt_Disney_Company         2518
Ford_Motor_Company              2353
Yahoo!                          1857
Microsoft                       1604
Comcast                         1428
General_Motors                  1211
Samsung                         1081
AT&T                            1081
T-Mobile                         913
Chrysler                         906
Fiat_Chrysler_Automobiles        876
LinkedIn                         854
DirecTV                          786
Time_Warner                      772
Audi                             768
Lucasfilm                        601
Intel                            572
International_Airlines_Group     555
Opel                             502
BMW                              490
Mercedes-Benz                    476
                                ...
Giant_Hypermarket                  1
Kabel_Deutschland                  1
HRL_Laboratories                   1
Lubrizol                           1
GTE                                1
Verizon_New_Jersey                 1
ReachLocal                         1
Bayer                              1
TTI,_Inc.                          1
GE_Aviation                        1
ImClone_Systems                    1
CyberSource                        1
Bank_Austria                       1
HSBC_Bank_USA                      1
Dermalogica                        1
Nickelodeon                        1
Thor_Industries                    1
Enel_Green_Power                   1
GE_Transportation                  1
GE_Healthcare                      1
Jeppesen                           1
Bayer_04_Leverkusen                1
The_J.M._Smucker_Company           1
Ford_Germany                       1
Trusteer                           1
Jayco,_Inc                         1
Big_Heart_Pet_Brands               1
GM_Financial                       1
GM_Korea                           1
Duracell                           1
Name: company1, Length: 440, dtype: int64

In [11]:
dataset["company2"].value_counts()

YouTube                          13001
Google                            6079
AT&T                              5074
General_Motors                    4655
Verizon_Communications            4306
Alexa_Internet                    3983
Amazon.com                        2977
LinkedIn                          2387
T-Mobile_US                       2015
Time_Warner                       1421
The_Walt_Disney_Company           1409
Chevrolet                         1287
DirecTV                           1185
PayPal                            1035
AOL                               1028
Microsoft                          915
HBO                                785
Jeep                               625
Audi                               614
Porsche                            599
NBCUniversal                       572
Lucasfilm                          556
International_Airlines_Group       555
Mercedes-Benz                      524
Marvel_Comics                      507
Boeing                             466
Warner_Bros.                       465
Viacom                             454
Nest_Labs                          447
British_Airways                    443
                                 ...
Big_Heart_Pet_Brands                 1
J.P._Morgan_&_Co.                    1
Jayco,_Inc                           1
TTI,_Inc.                            1
Lubrizol                             1
Verizon_New_Jersey                   1
Giant_Hypermarket                    1
Ameritech                            1
Kabel_Deutschland                    1
Fruit_of_the_Loom                    1
GE_Transportation                    1
GM_Korea                             1
Trusteer                             1
GE_Aviation                          1
ImClone_Systems                      1
Bayer_04_Leverkusen                  1
Visa_Inc.                            1
UniCredit                            1
HRL_Laboratories                     1
Thor_Industries                      1
Highbridge_Capital_Management        1
Dermalogica                          1
CyberSource                          1
HSBC_Bank_USA                        1
ReachLocal                           1
Bank_Austria                         1
Nickelodeon                          1
Bayer                                1
GTE                                  1
Jeppesen                             1
Name: company2, Length: 447, dtype: int64